[package]
name = "poly-naysayer"
version.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
documentation.workspace = true
keywords.workspace = true
include.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
